# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RideInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('current_location', models.CharField(max_length=200)),
                ('distance', models.IntegerField()),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_final_destination', to='rides.Destination')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ManyToManyField(related_name='rides_as_passenger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
